version: "3.4"
services:
  nginx:
    build: './docker/nginx/'
    container_name: base-nginx
    depends_on:
      - php
      - mysql
      - supervisor
    networks:
      - backend
    ports:
      - '${NGINX_PORT}:80'
    volumes:
      - ./source/:/var/www/html/
    restart: always
  php:
    build:
      context: './docker/php/'
      target: php
    container_name: base-php
    networks:
      - backend
    volumes:
      - ./source/:/var/www/html/
      - ./docker/php/config/config.ini:/usr/local/etc/php/conf.d/uploads.ini
    restart: always
  cronjob:
    build:
      context: './docker/php/'
      target: cron
    container_name: base-cronjob
    networks:
      - backend
    volumes:
      - ./source/:/var/www/html/
      - ./docker/php/config/config.ini:/usr/local/etc/php/conf.d/uploads.ini
    restart: always
  supervisor:
    build:
      context: './docker/php/'
      target: queue
    container_name: base-supervisor
    networks:
      - backend
    volumes:
      - ./source:/var/www/html/
      - ./docker/php/config/config.ini:/usr/local/etc/php/conf.d/uploads.ini
    restart: always
  mysql:
    image: mysql:8.0.23
    command: --default-authentication-plugin=mysql_native_password
    container_name: base-mysql
    ports:
      - '${DB_CONTAINER_PORT}:3306'
    networks:
      - backend
    volumes:
      - ./source/:/var/www/html/
      - ./source/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
    restart: always
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: base-phpmyadmin
    environment:
      - PMA_ARBITRARY=10
      - PMA_HOST=mysql
      - PMA_PORT=3306

    restart: always
    ports:
      - '${PHPMYADMIN_PORT}:80'
    networks:
      - backend

networks:
  backend:
